version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    image: smains/bodyledgerapi:latest
    depends_on:
      - db
    ports:
      - "8080:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__PostgresConnection: "Host=159.89.82.142;Database=bodyledger;Username=postgres;Password=H&yjs)2AAbHR&6yF"
    networks:
      - bodyledger-network
    restart: always

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H&yjs)2AAbHR&6yF
      POSTGRES_DB: bodyledger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
    networks:
      - bodyledger-network

volumes:
  postgres_data:

networks:
  bodyledger-network:



